export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const GET_COINDATA_SUCCESS = 'GET_COINDATA_SUCCESS'
export const GET_COINDATA_ERROR = 'GET_COINDATA_ERROR'

export const GET_COINSDATA_BEGIN = 'GET_COINSDATA_BEGIN'
export const GET_COINSDATA_SUCCESS = 'GET_COINSDATA_SUCCESS'
export const GET_COINSDATA_ERROR = 'GET_COINSDATA_ERROR'

export const ADD_PORTFOLIO_BEGIN = 'ADD_PORTFOLIO_BEGIN'
export const ADD_PORTFOLIO_SUCCESS = 'ADD_PORTFOLIO_SUCCESS'
export const ADD_PORTFOLIO_ERROR = 'ADD_PORTFOLIO_ERROR'

export const GET_PORTFOLIO_BEGIN = 'GET_PORTFOLIO_BEGIN'
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS'
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR'
