export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const GET_COINDATA_SUCCESS = 'GET_COINDATA_SUCCESS'
export const GET_COINDATA_ERROR = 'GET_COINDATA_ERROR'

export const GET_COINSDATA_BEGIN = 'GET_COINSDATA_BEGIN'
export const GET_COINSDATA_SUCCESS = 'GET_COINSDATA_SUCCESS'
export const GET_COINSDATA_ERROR = 'GET_COINSDATA_ERROR'

export const BUY_COIN_BEGIN = 'BUY_COIN_BEGIN'
export const BUY_COIN_SUCCESS = 'BUY_COIN_SUCCESS'
export const BUY_COIN_ERROR = 'BUY_COIN_ERROR'

export const GET_PORTFOLIO_BEGIN = 'GET_PORTFOLIO_BEGIN'
export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS'
export const GET_PORTFOLIO_ERROR = 'GET_PORTFOLIO_ERROR'
