export const UPDATE_WATCHLIST = 'UPDATE_WATCHLIST'
export const UPDATE_WATCHLIST_SUCCESS = 'UPDATE_WATCHLIST_SUCCESS'

export const GET_WATCHLISTDATA_BEGIN = 'GET_WATCHLISTDATA_BEGIN'
export const GET_WATCHLISTDATA_SUCCESS = 'GET_WATCHLISTDATA_SUCCESS'
export const GET_WATCHLISTDATA_ERROR = 'GET_WATCHLISTDATA_ERROR'