export const GET_COINSDATA_BEGIN = 'GET_COINSDATA_BEGIN'
export const GET_COINSDATA_SUCCESS = 'GET_COINSDATA_SUCCESS'
export const GET_COINSDATA_ERROR = 'GET_COINSDATA_ERROR'

export const ADD_WATCHLIST_BEGIN = 'ADD_WATCHLIST_BEGIN'
export const ADD_WATCHLIST_SUCCESS = 'ADD_WATCHLIST_SUCCESS'
export const ADD_WATCHLIST_ERROR = 'ADD_WATCHLIST_ERROR'

export const GET_WATCHLIST_BEGIN = 'GET_WATCHLIST_BEGIN'
export const GET_WATCHLIST_SUCCESS = 'GET_WATCHLIST_SUCCESS'
export const GET_WATCHLIST_ERROR = 'GET_WATCHLIST_ERROR'
